### ISSUE TITLE
Update package naming, archive or remove legacy packages

### ISSUE THREAD

**Issue by a-andreyev** [nemo-packaging/overview#2]
### Definetly could be archived/removed (due to dropping it from mer):
- statefs-git
- statefs-qt-git
- libdsme-git -- could be replaced with native arch package: https://www.archlinux.org/packages/community/x86_64/libdsme/

### Could be removed, since renamed packages are already provided (similar to `qt5-base, etc...` naming [[1], [2]]):

- libresource-git (replaced with meego-resource-git)
- libresourceqt-git (replaced with qt5-resource-git)

- qtquickcontrols-nemo-git (replaced with qt5-quickcontrols-nemo-git)

- qt-dbus-extended-git (replaced with qt5-dbus-extended-git)

- qt-mpris-git (replaced with qt5-mpris-git)

### To rename (still not renamed yet):

- qtaround-git —> qt5-around-git
- qt-mce-git —> qt5-mce-git
- qt-mlocale-git —> qt5-mlocale-git

- libusb-moded-qt-git —> qt5-usb-moded-git
- libngf-qt-git —> qt5-ngfd-git

- libconnman-qt-git —> qt5-connman-git

- libcontentaction-git —> nemo-qml-plugin-contentaction

- libiodata-git —> qt5-iodata-git

- timed-git —> qt5-timed-git

After that other packages deps should be updated (in semi-automated mode due to this log)

[1]: https://wiki.archlinux.org/index.php/Arch_package_guidelines#Package_naming
[2]: https://wiki.manjaro.org/index.php?title=Manjaro_Packaging_Standards#Package_naming_2

**Comment by NuLogicSystems** [comment]
OK, I took care of removing the duplicates that were replaced with renamed versions.
Why not just rename the existing repositories from within github itself rather than creating new ones? (settings > Repository name)
This way it would only be a mater of editing, and/or replacing, the existing files, and adding any additional files if needed.

**Comment by a-andreyev** [comment]
> Why not just rename the existing repositories from within github itself rather than creating new ones?

My bad, I probably should remove new and just rename old ones with new commits

**Comment by NuLogicSystems** [comment]
I already removed the old ones, I was thinking more along the lines of going forward. However,It was just a thought. Github does have a great little editor, and some really good tools for administration,  built right in.

**Comment by NuLogicSystems** [comment]
I renamed and fixed up the pkgbuild files for these repositories:
qtaround-git —> qt5-around-git
qt-mce-git —> qt5-mce-git
qt-mlocale-git —> qt5-mlocale-git
libusb-moded-qt-git —> qt5-usb-moded-git
libngf-qt-git —> qt5-ngfd-git
libconnman-qt-git —> qt5-connman-git

However, I'm not too sure about these last three being Qt5/qml source:
libcontentaction-git —> nemo-qml-plugin-contentaction
libiodata-git —> qt5-iodata-git
timed-git —> qt5-timed-git

**Comment by a-andreyev** [comment]
agree with the proposed rename:
libcontentaction-git —> nemo-qml-plugin-contentaction-git
libiodata-git —> qt5-iodata-git
timed-git —> qt5-timed-git

applied it and updated the patch from timed

going to close the issue at the moring after re-check

**Comment by a-andreyev** [comment]
just FYI:
I've [packaged](https://github.com/muhasturk/gitim/pull/18) handy python tool to clone all the repos at once:

```sh
yaourt -S python-gitim-git
python -m gitim --org nemo-packaging --dest /path/to/clone/repositories
```

hope it could be helpful for the future deployment.

Still checking the pkgbuilds for possible errors, will update the status today

**Comment by a-andreyev** [comment]
Updated deps and readme.md files accordingly. Closing for now, feel free to reopen
